### ISSUE TITLE
Investigate gcc -fpatchable-function-entry

### ISSUE THREAD

**Issue by namhyung** [namhyung/uftrace#1238]
Recent GCC added the -fpatchable-function-entry option to better support dynamic tracing.  We should investigate it and support the binaries too.

**Comment by honggyukim** [comment]
It would be really helpful if we have `-fpatchable-function-exit` as well in the future.

**Comment by honggyukim** [comment]
I also see that both GCC and Clang have `-fpatchable-function-entry` in the recent versions.

**Comment by honggyukim** [comment]
This option is also supported both in x86_64 and aarch64 as well.

**Comment by honggyukim** [comment]
alpine doesn't support `-pg` nor `-finstrument-functions`, but it supports `-fpatchable-function-entry`.
```
$ docker run -v $PWD:/uftrace -w /uftrace --rm -it alpine:3.13

/uftrace # apk add build-base

/uftrace # gcc -pg tests/s-abc.c
/usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find gcrt1.o: No such file or directory
collect2: error: ld returned 1 exit status

/uftrace # gcc -finstrument-functions tests/s-abc.c
/usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /tmp/cceEeFpD.o: in function `a':
s-abc.c:(.text+0x18): undefined reference to `__cyg_profile_func_enter'
/usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: s-abc.c:(.text+0x33): undefined reference to `__cyg_profile_func_exit'
/usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /tmp/cceEeFpD.o: in function `b':
s-abc.c:(.text+0x57): undefined reference to `__cyg_profile_func_enter'
/usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: s-abc.c:(.text+0x72): undefined reference to `__cyg_profile_func_exit'
/usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /tmp/cceEeFpD.o: in function `c':
s-abc.c:(.text+0x96): undefined reference to `__cyg_profile_func_enter'
/usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: s-abc.c:(.text+0xd2): undefined reference to `__cyg_profile_func_exit'
/usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /tmp/cceEeFpD.o: in function `main':
s-abc.c:(.text+0xfd): undefined reference to `__cyg_profile_func_enter'
/usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: s-abc.c:(.text+0x145): undefined reference to `__cyg_profile_func_exit'
collect2: error: ld returned 1 exit status
```
But `-fpatchable-function-entry=N` compiles successfully.
```
/uftrace # gcc -fpatchable-function-entry=5 tests/s-abc.c
```
https://gitlab.alpinelinux.org/alpine/aports/-/issues/9191

**Comment by namhyung** [comment]
That explains so many build failures in the #1298.

**Comment by honggyukim** [comment]
Yes, right. It explains the failures at https://github.com/namhyung/uftrace/issues/1298#issuecomment-895860617.

**Comment by honggyukim** [comment]
https://godbolt.org/z/rc1rs7hqK shows the different binary outputs for various traceable options.
